### ISSUE TITLE
pcs cluster status != pcs status cluster

### ISSUE THREAD

**Issue by johnmccabe** [feist/pcs#35]
Seeing the following behavior with 0.9.115 on a CMAN/Corosync/Pacemaker cluster on RHEL64 (using the pcs release downloaded from github).

`pcs status cluster` behaves as expected, but `pcs cluster status` also includes a warning about pcsd not running (the help page suggests the command is an alias of `pcs status cluster` so I would have expected it to behave the same in both cases?).

```
[root@node0 pcs-0.9.115]# pcs status cluster
Cluster Status:
 Last updated: Mon Mar 10 10:28:49 2014
 Last change: Mon Mar 10 10:25:42 2014 via crm_attribute on node0-priv
 Stack: cman
 Current DC: node0-priv - partition with quorum
 Version: 1.1.10-1.el6_4.4-368c726
 2 Nodes configured
 12 Resources configured
```
versus
```
[root@node0 pcs-0.9.115]# pcs cluster status
Cluster Status:
 Last updated: Mon Mar 10 10:30:09 2014
 Last change: Mon Mar 10 10:25:42 2014 via crm_attribute on node0-priv
 Stack: cman
 Current DC: node0-priv - partition with quorum
 Version: 1.1.10-1.el6_4.4-368c726
 2 Nodes configured
 12 Resources configured

PCSD Status:
Error: no nodes found in corosync.conf
```
Thanks!

**Comment by tomjelinek** [comment]
Thank you for reporting the issue. It has been fixed as a part of another fix in https://github.com/feist/pcs/commit/8be3ac4314f6587efb5d0f25d665f6c9250ccee8
