### ISSUE TITLE
newlines stripped from attribute values

### ISSUE THREAD

**Issue by phemmer** [feist/pcs#39]
When trying to use a resource attribute with a newline character in it, the newline is converted into a space.

```
# pcs resource create test1 ocf:pacemaker:Dummy fake=hello$'\n'world
# cibadmin -Q | grep world
          <nvpair id="test1-instance_attributes-fake" name="fake" value="hello world"/>
```

**Comment by idevat** [comment]
Described behavior is not a bug. There cannot be a new line character in xml attribute, new line must be normalized (according to the XML spec, section 3.3.3 https://www.w3.org/TR/REC-xml/#AVNormalize).

If it is desired to have value="hello\nworld" it can be achieved by:
```
# pcs resource create test1 ocf:pacemaker:Dummy fake=hello$'\\n'world
# cibadmin -Q | grep world
   <nvpair id="test1-instance_attributes-fake" name="fake"
value="hello\nworld"/> 
```
It is up to fence / resource agents to handle \n correctly.

**Comment by phemmer** [comment]
I would still argue that there is a bug here. `pcs` should be taking that literal newline and converting it.
