### ISSUE TITLE
Does not support utilization parameters

### ISSUE THREAD

**Issue by phemmer** [feist/pcs#41]
Pacemaker has support for utilization attributes as described in [Chapter 11 of Configuration Explained](http://clusterlabs.org/doc/en-US/Pacemaker/1.1-pcs/html/Pacemaker_Explained/_utilization_attributes.html)

It would be nice if PCS had the ability to set these attributes so that we would not have to configure them manually.

For example, if I want to set the `cpu` utilization attribute, I currently have to do the following:
```
pcs resource create dummy1 ocf:pacemaker:Dummy meta target-role=stopped
crm_resource -r dummy1 -z -p cpu -v 1000
pcs resource start dummy1
```

**Comment by ondrejmular** [comment]
Support for utilization attributes has been added in commit 1b8b40f87d307d6cf831b9e9a056d43a314ffd80
