### ISSUE TITLE
pcs ssh to pcsd timeout too long

### ISSUE THREAD

**Issue by tbsky** [feist/pcs#52]
i am testing pacemaker with sl linux 7.0. I create vmware vm,  install sl 7.0 at vmware vm. and above the vmware vm I create linux kvm which is controlled by pacemaker. 

  the environment is unstable, vmware vm often hang. so I think it is a great environment for testing pacemaker.
 
 I found pcsd cause trouble when one of the vmware vm is hang. (the hung vm will response ssh connect but with no further reply)

when I issue  command "pcs cluster status", the pcs script try to ssh to hung vm and hang there for several minutes. 

is there a proper way to disable pcsd completely under el 7.0? or maybe pcs should use ssh with a proper timeout value?

**Comment by feist** [comment]
We don't currently have a command that allows you to get the full status without pcsd, however you can run 'pcs status resources' or 'pcs status nodes' to only get the resource or node status.  You can also use the command 'crm_mon' to view the pacemaker cluster status.

**Comment by tbsky** [comment]
hi:
    yes I can use "crm_mon -1" to get old style "pcs status" result.  (to check which node the resource started ). but I prefer pcs to do all the jobs if possible :)
