### ISSUE TITLE
I can't install pcs on debian wheezy

### ISSUE THREAD

**Issue by caje0004** [feist/pcs#53]
service pcsd start says:
pcsd unrecognized service.

pcs status says
Error: unable to locate command: /usr/sbin/corosync-cmapctl

Thanks.

**Comment by feist** [comment]
Can you verify that corosync is installed?  And if it is installed, can you find out where corosync-cmapctl is located?

**Comment by caje0004** [comment]
Yes, I´ve installed corosync. These are the commands installed:
corosync             corosync-fplay       corosync-pload
corosync-blackbox    corosync-keygen      corosync-quorumtool
corosync-cfgtool     corosync-notifyd     
corosync-cpgtool     corosync-objctl

**Comment by caje0004** [comment]
Hello.

Corosync is installed but corosync-cmapctl doesn't exist. These are the commands that exist:
corosync             corosync-fplay       corosync-pload
corosync-blackbox    corosync-keygen      corosync-quorumtool
corosync-cfgtool     corosync-notifyd     
corosync-cpgtool     corosync-objctl 

Thanks.

**Comment by tomjelinek** [comment]
Hello, I changed cman/corosync detection in https://github.com/feist/pcs/commit/9e19af588be49ee7c11a158e01c23dffc33791fe, which (hopefully) fixes this issue.
