### ISSUE TITLE
python scripts

### ISSUE THREAD

**Issue by Thermi** [feist/pcs#56]
Hello,

I noticed that the python scripts in pcs are always called using "python $scriptname".
This does not work on distributions and platforms where python is actually python3, not python2.
Do you mind changing the scripts to be called using python2, not just python?
For example on Arch Linux this is a problem and I can't package pcs for that distribution
because of that problem

Kind regards,
Thermi

**Comment by tomjelinek** [comment]
Hello,

This has been fixed in https://github.com/feist/pcs/commit/6cbb5abea384497cc04797a0c30819c04ad41471 in accordance with PEP 394.

Thank you for reporting the issue.
