### ISSUE TITLE
[Question] About a method to move pcsd on RHEL6.

### ISSUE THREAD

**Issue by HideoYamauchi** [feist/pcs#74]
We are going to move pcsd on RHEL6.

Our environment put corosync2.x and Pacemaker1.1.13 together.

We do not seem to be able to move pcsd by the combination of us on RHEL6 as far as I look at a manual and the source of RH.
We put pcsd in RHEL6 environment, but service pcsd start is not really completed.
(We did not install cman.)

We want to know the details of the method to move pcsd in our environment.
Or, by this combination, can we not move pcsd?

If there is a link serving as a reference, please tell us.

Best Regards,
Hideo Yamauchi.

**Comment by tomjelinek** [comment]
If you want to use pcs on RHEL6 with corosync2 and no cman, you need pcs 0.9.145 or newer. It also fixes a few other RHEL6 issues.
Are you saying you are not able to start pcsd service? Are there any error messages?

Best Regards,
Tomas

**Comment by HideoYamauchi** [comment]
Hi Tomas,

We wanted to start pcsd on RHEL6 without using CMAN.
We try it in combination with CMAN.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Tomas,

I misread your comment.
I put coosync2 and Pacemaker1.1.13 and pcs and pcsd together on RHEL6.7 and confirmed start.
Let me confirm it again just to make sure.

When I combine new pcs with corosync2, is my understanding that cman is unnecessary for right?

Best Regards,
Hideo Yamauchi.

**Comment by tomjelinek** [comment]
Hi Hideo,

You are right. Cman is unnecessary when you use corosync2 and new pcs.

Best Regards,
Tomas

**Comment by HideoYamauchi** [comment]
Hi Tomas,

Okay!
Many Thanks!

Hideo Yamauchi.
