### ISSUE TITLE
pcs status returns IndexError: list index out of range

### ISSUE THREAD

**Issue by jematthe** [feist/pcs#79]
I updated pcs, and now pcs doesn't work for me:

[root@g5se-f3efce log]# pcs status
Cluster name: cl-g5se-f3efce
Traceback (most recent call last):
  File "/usr/sbin/pcs", line 155, in <module>
    main(sys.argv[1:])
  File "/usr/sbin/pcs", line 147, in main
    status.status_cmd(argv)
  File "/usr/lib/python2.6/site-packages/pcs/status.py", line 13, in status_cmd
    full_status()
  File "/usr/lib/python2.6/site-packages/pcs/status.py", line 53, in full_status
    if utils.corosyncPacemakerNodeCheck():
  File "/usr/lib/python2.6/site-packages/pcs/utils.py", line 1975, in corosyncPacemakerNodeCheck
    pm_nodes = getPacemakerNodesID()
  File "/usr/lib/python2.6/site-packages/pcs/utils.py", line 1970, in getPacemakerNodesID
    pm_nodes[node_info[0]] = node_info[1]
IndexError: list index out of range

This is what I have installed:

[root@g5se-f3efce log]# yum info pcs
Installed Packages
Name        : pcs
Arch        : x86_64
Version     : 0.9.139
Release     : 9.el6_7.2
Size        : 14 M
Repo        : installed
From repo   : corespace-centos-6-updates-x86_64
Summary     : Pacemaker Configuration System
URL         : http://github.com/feist/pcs
License     : GPLv2
Description : pcs is a corosync and pacemaker configuration tool.  It permits users to
            : easily view, modify and created pacemaker based clusters.

I erased this pcs version and reinstalled an earlier version, and it worked. See below:

[root@g5se-f3efce Packages]# pcs status
Cluster name: cl-g5se-f3efce
Last updated: Thu Feb 18 14:41:34 2016
Last change: Thu Feb 18 11:46:49 2016 via crm_resource on g5se-f3efce
Stack: cman
Current DC: g5se-f3efce - partition with quorum
Version: 1.1.11-97629de
1 Nodes configured
4 Resources configured

Online: [ g5se-f3efce ]

Full list of resources:

 sw-ready-g5se-f3efce   (ocf::pacemaker:GBmon): Started g5se-f3efce
 meta-data      (ocf::pacemaker:GBmon): Started g5se-f3efce
 netmon (ocf::heartbeat:ethmonitor):    Started g5se-f3efce
 ClusterIP      (ocf::heartbeat:IPaddr2):       Stopped

[root@g5se-f3efce Packages]# yum info pcs
Installed Packages
Name        : pcs
Arch        : noarch
Version     : 0.9.90
Release     : 1.0.1.el6.centos
Size        : 457 k
Repo        : installed
From repo   : /pcs-0.9.90-1.0.1.el6.centos.noarch
Summary     : Pacemaker Configuration System
URL         : http://github.com/feist/pcs
License     : GPLv2
Description : pcs is a corosync and pacemaker configuration tool.  It permits users to
            : easily view, modify and created pacemaker based clusters.

**Comment by tomjelinek** [comment]
This bug manifests itself only in one-node cman clusters and has been fixed in pcs 0.9.148 https://github.com/feist/pcs/commit/b1da1d15576b855b0731357c60457962e71d7feb
Thank you for reporting the issue, though.

**Comment by jematthe** [comment]
Thank you. I have downloaded the source and did the make install for the 0.9.148 version. I no longer have this problem.

I have a ClusterIP location constraint in my cluster. When I remove the constraint, then not long after,  my network interface bounces (or my system restarts, I'm not sure yet and need to check; it's a VM).

I tried the 0.9.149 version as well and had the same result. I need to investigate my system, but I did not have this problem when removing the constraint with the 0.9.90 pcs version.

I will investigate my system further, but are there any major changes between 0.9.90 and 0.9.148/9?

Thank you for your help.

**Comment by tomjelinek** [comment]
There is a lot of changes between 0.9.90 and 0.9.148 but from the top of my head I cannot think about anything that would cause this. I suggest you asking on users@clusterlabs.org mailing list.

**Comment by jematthe** [comment]
I have been asking on that mailing list. I think there is some complication between the way our daemon has been clearing or creating the constraint in the past and how pcs and/or pacemaker work now. Thank you for your input.

**Comment by jematthe** [comment]
One last question: do you know when a pcs version with this fix will become available in the CentOS and RHEL repositories, as opposed to one having to download 0.9.149 from here and make install'ing? 0.9.139 seems to be the latest in the repositories.

**Comment by tomjelinek** [comment]
Should be available in the next release, but I don't really know when it is going to be released.
