### ISSUE TITLE
Question : About confirm command.

### ISSUE THREAD

**Issue by HideoYamauchi** [feist/pcs#84]
Hi All,

When I use the confirm command, Pacemaker of the node is stopped when a node to intend for does not stop.
Is this movement a specification?

 * I thought that the confirm command could acquire the state of the node.(I thought that the practice of the command never stopped Pacemaker.)
 * Is this understanding wrong?

[root@rh72-01 ~]# pcs cluster start --all
rh72-02: Starting Cluster...
rh72-01: Starting Cluster...

[root@rh72-01 ~]# pcs status
Cluster name: cluster1
WARNING: no stonith devices and stonith-enabled is not false
Last updated: Thu Feb 25 09:10:07 2016          Last change: Thu Feb 25 09:08:54 2016 by hacluster via crmd on rh72-01
Stack: corosync
Current DC: rh72-01 (version 1.1.14-70404b0) - partition with quorum
2 nodes and 0 resources configured

Online: [ rh72-01 rh72-02 ]

Full list of resources:

PCSD Status:
  rh72-01: Online
  rh72-02: Online

Daemon Status:
  corosync: active/disabled
  pacemaker: active/disabled
  pcsd: active/disabled

[root@rh72-01 ~]# pcs stonith confirm rh72-02
Node: rh72-02 confirmed fenced

[root@rh72-02 ~]# ps -ef |grep pace
root      1581   867  0 09:06 pts/0    00:00:00 grep --color=auto pace
[root@rh72-02 ~]# ps -ef |grep coro
root      1478     1  1 09:05 ?        00:00:00 corosync
root      1583   867  0 09:06 pts/0    00:00:00 grep --color=auto coro

Best Regards,
Hideo Yamauchi.

**Comment by tomjelinek** [comment]
Hi Hideo,

What are you trying to achieve? `pcs stonith confirm` is supposed to be run when a node has been fenced or powered off but pacemaker does not know about that for some reason.

Best Regards,
Tomas

**Comment by HideoYamauchi** [comment]
Hi Tomas,

Sorry, my English may confuse you.

I thought that Pacemaker which worked did not stop only by having executed confirm command.
Does it mean that your answer stops?

- pcs stonith fence really carries out stonith.
- pcs confirm did not really carry out stonith, but stopped Pacemaker.

Best Regards,
Hideo Yamauchi.

**Comment by tomjelinek** [comment]
Hi Hideo,

`pcs stonith fence` carries out stonith, that means it fences a node. You can use it to fence a node manually.
`pcs stonith confirm` only tells pacemaker a node was fenced. As a side effect pacemaker on the node gets stopped. You definitely should not run this with a node where pacemaker is still running, as mentioned in pcs help and man page.
Usually it is not needed to run these commands unless cluster gets seriously broken.

Hope that helps,
Tomas

**Comment by HideoYamauchi** [comment]
Hi Tomas,

I do not use the confirm command alone.
After having executed fence command, I use it for confirmation.

Many thanks,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Because a discussion was over, this is closed.
