### ISSUE TITLE
monkey-lib ruby gem used?

### ISSUE THREAD

**Issue by boutil** [feist/pcs#86]
Hi!

I see that the Gemfile is listing monkey-lib, but it doesn't seem to be used anywhere in the project.
Since monkey-lib is dead upstream and doesn't work well with Ruby2.3, do you think it can be safely remove from the Gemfile and the gem install command of the Makefile?

**Comment by tomjelinek** [comment]
Hi!

Thank you for pointing this out. Monkey-lib was included as a dependency of sinatra-sugar, which we don't use either. So I removed both gems in https://github.com/feist/pcs/commit/83025f6fc5bc805d42ab8f0179f0fb662038cb4c
