### ISSUE TITLE
Replace pcsd TLS certificate for port 2224?

### ISSUE THREAD

**Issue by allywilson1** [feist/pcs#89]
I can see in ssl.rb it will generate a dynamic certificate if one doesn't already exist, but I must be going blind, as I don't see a way to specify my own certificates? I can't even see the certificate files it generates dynamically...

**Comment by allywilson1** [comment]
Nevermind, I found it after seeing:
```

CRT_FILE = PCSD_VAR_LOCATION + 'pcsd.crt'
KEY_FILE = PCSD_VAR_LOCATION + 'pcsd.key'
```
in the settings.rb file.

/var/lib/pcsd/pcsd.crt
/var/lib/pcsd/pcsd.key

**Comment by tomjelinek** [comment]
You can use `pcs pcsd certkey` and `pcs pcsd sync-certificates` commands or replace certificates by hand in `/var/lib/pcsd/pcsd.crt` and `/var/lib/pcsd/pcsd.key`.
